### ISSUE TITLE
Fuel gauge sometimes goes out of sync

### ISSUE THREAD

**Issue by matejdro** [GamingCoookie/dv-multiplayer-continued#12]
**Describe the bug**

Minor bug: sometimes fuel gauge goes out of sync / stops updating.  For example, throughout the whole freight haul, fuel meter in the DE2 was at 100%, while other players reported it at around 66% and dropping.

Presumably it also happens with other gauges, but we did not check that (we can check it again if required).

**To Reproduce**
1. Go on a long haul route with multiple players (all in the same locomotive)
2. Have everyone look at the fuel gauge

**Desktop (please complete the following information):**
 - OS: Windows 10 on host and all clients
 - Mod Version: DV Build #92, Mod 1.3.8.1 on host and all clients

**Comment by GamingCoookie** [comment]
Thank you for the issue description. Although on my local repo this has been fixed already :')
