### ISSUE TITLE
Couplings of locomotives and/or wagons can sometimes "fuse" into each other

### ISSUE THREAD

**Issue by matejdro** [GamingCoookie/dv-multiplayer-continued#13]
**Describe the bug**

This one is pretty weird and we could only reproduce it once. Check the screenshot below, we have attached double DE2 to pretty long train on a rail yard and attempted to push it. Weirdly, our train only pushed some carts, others stayed put, resulting in coupling parts of some cars and later even the locomotive phasing into one another.

We have managed to solve the issue with a third DE2 on the other side of the train that pulled the train and it unstuck everything.

It is possible that is related to the double DE2 (multiple units are after all not officially supported yet), but the double combination worked fine except for this issue. Feel free to close the issue if it is invalid.

**To Reproduce**
1. Pick a fairly long train on a rail yard
2. Attach double DE2 on one side
3. Attempt to push the train backwards

**Screenshots**

![fuse1](https://user-images.githubusercontent.com/507922/171702389-f5915cd2-9c0b-4421-bcc9-a44bd8abed8f.jpg)

![fuse2](https://user-images.githubusercontent.com/507922/171702413-17449533-a142-4122-9b6f-d51b2191e795.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 on host and all clients
 - Mod Version: DV Build #92, Mod 1.3.8.1 on host and all clients

**Comment by GamingCoookie** [comment]
Can't repro and I am pretty sure this is a vanilla bug
