### ISSUE TITLE
Game freezes after disconnecting

### ISSUE THREAD

**Issue by matejdro** [GamingCoookie/dv-multiplayer-continued#15]
**Describe the bug**

After disconnecting from a server, my game froze. Skimming through logs, those are the two errors that I found, but not sure if related (full log is below):

```
NetworkTrainManager doesn't implement AllowAutoCreate method, assuming 'false' 
```

```
NullReferenceException: Object reference not set to an instance of an object
  at NetworkTrainSync.Update () [0x00005] in <a2c0a870e73b4e80a2163bfd3f557824>:0 
```

**To Reproduce**
1. Connect to a server
2. Open multiplayer menu and select "Disconnect"

**Desktop (please complete the following information):**
 - OS: Windows 10 on host and all clients
 - Mod Version: DV Build #92, Mod 1.3.8.1 on host and all clients

**Additional context**

Full log: 
[Disconnect freeze.log](https://github.com/GamingCoookie/dv-multiplayer-continued/files/8826711/Disconnect.freeze.log)

**Comment by GamingCoookie** [comment]
fixed with v1.5.0
