### ISSUE TITLE
Turntables do not sync when moved by client

### ISSUE THREAD

**Issue by matejdro** [GamingCoookie/dv-multiplayer-continued#18]
**Describe the bug**

Turntables only appear to sync when they are moved by the host. If connected client attempts to move it, they only move for them, host does not see any movement.

**To Reproduce**
1. Host a server
2. Have someone connect to you
3. Both go to any turntable
4. Have connected client turn the turntable

**Expected behavior**

Turntable should turn for both players.

**Screenshots**

If host drives a locomotive on a turntable after it was moved by a client, lack of sync can ensue hilarious scenes:

![image](https://user-images.githubusercontent.com/507922/172229883-4f154e2c-6d88-4834-86dc-b5024a78b815.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 on host and all clients
 - Mod Version: DV Build #92, Mod 1.3.8.1 on host and all clients

**Comment by GamingCoookie** [comment]
Sorry, I can't reproduce this issue :/

**Comment by matejdro** [comment]
This is still happening in v1.5.0.2. Maybe it only happens on specific turntables? For us, it happens on Steel Meel.
