### ISSUE TITLE
Minor: light switches do not sync between players

### ISSUE THREAD

**Issue by matejdro** [GamingCoookie/dv-multiplayer-continued#19]
**Describe the bug**

Light switches (Cab Light, Headlights) do not appear to sync between players, at least not on DE2.

This is super minor for now (it does not affect the simulation, so every player can just easily turn on lights for themselves), but it might become more important with the upcoming day/night cycle.

**To Reproduce**
1. Have one player turn on locomotive lights
2. Have another player observe
3. Lights do not turn on

**Expected behavior**

Light state should be synchronized between players

**Desktop (please complete the following information):**
 - OS: Windows 10 on host and all clients
 - Mod Version: DV Build #92, Mod 1.3.8.1 on host and all clients

**Comment by GamingCoookie** [comment]
All buttons and switches will be synchronized in 1.4 :)
