### ISSUE TITLE
Server erection consultation

### ISSUE THREAD

**Issue by IGBT-001** [GamingCoookie/dv-multiplayer-continued#21]
Hello, as mentioned in the question, I have a cloud server in my hand, how can I modify the code to achieve the online effect of the game?
After all, if you use a peer-to-peer server, the game experience will be very bad when the network is not good. I want to try to set up a separate game server. All players connect to this server, and the game experience will be much better.
Use Google Translate for the above content!

你好，如题所述，我手里有一个云服务器，我该如何修改代码才能实现游戏的联机效果呢？
毕竟如果使用点对点架设服务器，网络不好的情况下游戏体验是非常糟糕的，我想尝试采用架设一个单独的游戏服务器，所有玩家连接这个服务器，游戏体验效果会好很多。
以上内容使用谷歌翻译！

**Comment by GamingCoookie** [comment]
Hi, that's a feature to be implemented at a later time! Currently it only works peer-to-peer

**Comment by GamingCoookie** [comment]
dedicated server implemented but not quite fully functional, I will close this though
