### ISSUE TITLE
Dedicated server program

### ISSUE THREAD

**Issue by GamingCoookie** [GamingCoookie/dv-multiplayer-continued#24]

**Comment by zakwear** [comment]
@GamingCoookie How would you describe the strategy for a dedicated server? Would a DSP be a DV client, or other kind of standalone program? I might be interested in contributing.

**Comment by GamingCoookie** [comment]
I already have done quite a lot of work, but one of my harddrives half quit working so until I get a new one I can't push anything. The data isn't lost, I just need to backup it to a new harddrive

**Comment by zakwear** [comment]
Oh cool, excited to check it out whenever you get the chance to recover. We have a small group trying to migrate from Railroads Online.

**Comment by MorriTheDragon** [comment]
> I already have done quite a lot of work, but one of my harddrives half quit working so until I get a new one I can't push anything. The data isn't lost, I just need to backup it to a new harddrive
> 
> Edit: oh and it's an exe and it basically designates one player as the "host"

Would you be fine if I donated you a new hard drive? :D

**Comment by GamingCoookie** [comment]
> Would you be fine if I donated you a new hard drive? :D

I would be, yeah I already have a new one but tbh I am not doing any work rn on the mod, probably not until simulator releases and if anything it would be a preview version of what is currently finished
