### ISSUE TITLE
UPnP support

### ISSUE THREAD

**Issue by Pandapip1** [GamingCoookie/dv-multiplayer-continued#50]
## Is your feature request related to a problem? Please describe.

Manually setting up port forwarding is not something that non-technical users are easily going to be able to do. Adding support for Universal Plug and Play (UPnP) will allow the setup experience to be a lot smoother.

## Describe what the feature is that you'd like

See above.

## Describe alternatives you've considered

*N.A.* Either UPnP support will be added or it won't be.

## Additional context

The readme will need to be updated to remove the line that says UPnP is not supported.

**Comment by GamingCoookie** [comment]
I am sorry but this here is discontinued. Look at this https://github.com/AMacro/dv-multiplayer please
