### ISSUE TITLE
Stuck on "Loading Savegame"

### ISSUE THREAD

**Issue by TheKK50** [GamingCoookie/dv-multiplayer-continued#9]
Me and my friend have just downloaded the mod, but when we're trying to connect it gets stuck on "Loading savegame". Both of us are in the newest version of the game and plugin and Win10 64bit.

**Comment by GamingCoookie** [comment]
Could you provide me with logs please? They are located in AppData/LocalLow/Altfuture/Derail Valley

**Comment by TheKK50** [comment]
Sorry a bit late, but here it is.

[Player-prev.log](https://github.com/GamingCoookie/dv-multiplayer-continued/files/8465529/Player-prev.log)

**Comment by GeekAndProud** [comment]
Pressing the menu button fixes this

**Comment by GamingCoookie** [comment]
> Sorry a bit late, but here it is.
> 
> [Player-prev.log](https://github.com/GamingCoookie/dv-multiplayer-continued/files/8465529/Player-prev.log)

Sorry, but in that log there was no server ever open or connected

**Comment by GamingCoookie** [comment]
But I would say it's due to the extra mods. I believe this mod only works fine together with the passenger jobs mod. All players need to have the same set of mods if you want to use extra mods anyway (disabling doesn't work in case someone has one extra)
